### PR TITLE
moved all functions to seperate files

### PR DESCRIPTION
**Pull request by TheMockingJay1013**
have moved all functions to separate files . main.cpp only contains main() and GRID

### CODE REVIEW

**Comment by adk7712** [comment]
@TheMockingJay1013 please make sure to resolve all the conflicts

**Comment by TheMockingJay1013** [comment]
> @TheMockingJay1013 please make sure to resolve all the conflicts

conflicts resolved , pls check if the code still works as expected

**Comment by TheMockingJay1013** [comment]
It is my first time contributing to  an open source project . Thank you for the chance

**Comment by TheMockingJay1013** [comment]
Also i have made changes to the structure of collapse() and printboard() { just added a parameter GRID}

**Comment by adk7712** [comment]
@TheMockingJay1013 Seems to be working. Merged! Thank you for sparing your time.

**Comment by TheMockingJay1013** [comment]
> @TheMockingJay1013 Seems to be working. Merged! Thank you for sparing your time.

It was my time contributing to open source .So thank you too for the chance

**Pull request merged**
